/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join the waitlist
         * @description Idempotent on email. Rate limited to 5 requests/minute/IP.
         */
        post: operations["WaitlistController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboard a client (employer) */
        post: operations["OnboardingController_onboardClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/contractor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboard a contractor (worker) */
        post: operations["OnboardingController_onboardContractor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description CLIENT = an employer paying contractors, CONTRACTOR = a worker getting paid.
         * @enum {string}
         */
        AccountType: "CLIENT" | "CONTRACTOR";
        JoinWaitlistDto: {
            /** @example jane@acme.io */
            email: string;
            /**
             * @description CLIENT = an employer paying contractors, CONTRACTOR = a worker getting paid.
             * @example CLIENT
             */
            type: components["schemas"]["AccountType"];
            name?: string;
            company?: string;
            country?: string;
        };
        OnboardClientDto: {
            /** @example jane@acme.io */
            email: string;
            /** @example Jane Doe */
            name: string;
            /** @example Acme Inc */
            company: string;
            /** @example Nigeria */
            country: string;
            /** @example 12 */
            teamSize?: number;
        };
        OnboardContractorDto: {
            /** @example kwabena@work.io */
            email: string;
            /** @example Kwabena Mensah */
            name: string;
            /** @example Ghana */
            country: string;
            /**
             * @example GHS
             * @enum {string}
             */
            payoutCurrency: "USDC" | "NGN" | "KES" | "GHS" | "ZAR";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WaitlistController_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinWaitlistDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OnboardingController_onboardClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardClientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OnboardingController_onboardContractor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardContractorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
