/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which sign-in methods are available (so the web app only shows configured ones) */
        get: operations["AppController_authProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join the waitlist
         * @description Idempotent on email. Rate limited to 5 requests/minute/IP.
         */
        post: operations["WaitlistController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboard the signed-in user as an employer (creates their organization) */
        post: operations["OnboardingController_onboardClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/contractor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboard the signed-in user as a contractor (worker) */
        post: operations["OnboardingController_onboardContractor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every organization you belong to, with your role, and which one is active */
        get: operations["OrganizationsController_list"];
        put?: never;
        /** Create another organization (you become its owner; a treasury is provisioned; it becomes active) */
        post: operations["OrganizationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit the active organization's name, logo, country or team size (owner/admin) */
        patch: operations["OrganizationsController_update"];
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user with their organization / contractor profile and wallet state */
        get: operations["MeController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry on-chain activation for the signed-in user's wallet(s) */
        post: operations["MeController_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/fund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint test USDC into one of the caller’s wallets (testnet only) */
        post: operations["MeController_fund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send USDC from one of the caller’s wallets, with an optional memo */
        post: operations["MeController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pay a contractor from your organization treasury (idempotent) */
        post: operations["PaymentsController_pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your ledger — money actions you initiated or received */
        get: operations["PaymentsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contractors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contractors the active organization works with: on a payroll roster or paid before */
        get: operations["ContractorsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contractors/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find an onboarded contractor by email, so an employer can pay them (org members) */
        get: operations["ContractorsController_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether image uploads are configured (public) */
        get: operations["UploadsController_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign a direct-to-Cloudinary image upload for the signed-in user */
        post: operations["UploadsController_sign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payroll/definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Payroll definitions (rosters) for the active organization */
        get: operations["PayrollController_listDefinitions"];
        put?: never;
        /** Create a payroll definition (owner/admin) */
        post: operations["PayrollController_createDefinition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payroll/definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a definition (owner/admin) */
        delete: operations["PayrollController_deleteDefinition"];
        options?: never;
        head?: never;
        /** Update a definition (owner/admin) */
        patch: operations["PayrollController_updateDefinition"];
        trace?: never;
    };
    "/api/payroll/definitions/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add or update a contractor on the roster, by id or email (owner/admin) */
        post: operations["PayrollController_upsertItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payroll/definitions/{id}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a contractor from the roster (owner/admin) */
        delete: operations["PayrollController_removeItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payroll/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs for the active organization, newest first, with lines */
        get: operations["PayrollController_listRuns"];
        put?: never;
        /** Draft a run from a definition or explicit lines (owner/admin) */
        post: operations["PayrollController_createRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payroll/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One run with its lines */
        get: operations["PayrollController_getRun"];
        put?: never;
        post?: never;
        /** Discard a draft run (owner/admin) */
        delete: operations["PayrollController_discard"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payroll/runs/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a draft run: owner/admin, treasury must cover the total */
        post: operations["PayrollController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payroll/runs/{id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute an approved run, or retry the failed lines of a partial one (owner/admin) */
        post: operations["PayrollController_execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The active organization's treasury: when it was last checked against the chain, and open discrepancies */
        get: operations["ReconciliationController_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile the active organization's treasury now (owner/admin) */
        post: operations["ReconciliationController_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliation/discrepancies/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a discrepancy as looked at (owner/admin) */
        post: operations["ReconciliationController_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cashouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your cash-out requests, newest first (contractors) */
        get: operations["CashoutsController_list"];
        put?: never;
        /** Request a cash-out of USDC to your payout currency; recorded, paid out when the off-ramp is live */
        post: operations["CashoutsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cashouts/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an open cash-out request */
        post: operations["CashoutsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description CLIENT = an employer paying contractors, CONTRACTOR = a worker getting paid.
         * @enum {string}
         */
        AccountType: "CLIENT" | "CONTRACTOR";
        JoinWaitlistDto: {
            /** @example jane@acme.io */
            email: string;
            /**
             * @description CLIENT = an employer paying contractors, CONTRACTOR = a worker getting paid.
             * @example CLIENT
             */
            type: components["schemas"]["AccountType"];
            name?: string;
            company?: string;
            country?: string;
        };
        OnboardClientDto: {
            /**
             * @description Organization name. Defaults to "<name>'s Organization".
             * @example Acme Inc
             */
            company?: string;
            /** @example Nigeria */
            country?: string;
            /** @example 12 */
            teamSize?: number;
            /**
             * @description Logo URL from a signed upload (POST /api/uploads/sign).
             * @example https://res.cloudinary.com/disburs/image/upload/v1/disburs/org-logos/….png
             */
            logo?: string;
        };
        OnboardContractorDto: {
            /** @example Kwabena Mensah */
            name: string;
            /** @example Ghana */
            country: string;
            /**
             * @example GHS
             * @enum {string}
             */
            payoutCurrency: "USDC" | "NGN" | "KES" | "GHS" | "ZAR";
            /**
             * @description Payee type. Defaults to INDIVIDUAL.
             * @default INDIVIDUAL
             * @enum {string}
             */
            type: "INDIVIDUAL" | "BUSINESS";
            /**
             * @description Required when type = BUSINESS.
             * @example Acme Logistics Ltd
             */
            companyLegalName?: string;
            /**
             * @description Required when type = BUSINESS.
             * @example 12 Ring Road, Accra, Ghana
             */
            businessAddress?: string;
        };
        CreateOrganizationDto: {
            /** @example Acme Studio */
            name: string;
            /** @example Kenya */
            country?: string;
            /** @example 8 */
            teamSize?: number;
            /** @description Logo URL from a signed upload. */
            logo?: string;
        };
        UpdateOrganizationDto: {
            /** @example Acme Studio */
            name?: string;
            /** @example Kenya */
            country?: string;
            /** @example 8 */
            teamSize?: number;
            /** @description Logo URL from a signed upload. */
            logo?: string;
        };
        FundDto: {
            /**
             * @description Public key of a wallet the caller owns.
             * @example GAP24RSA…
             */
            publicKey: string;
            /**
             * @description Amount to mint. Defaults to 100.
             * @example 100
             */
            amount?: string;
        };
        SendDto: {
            /**
             * @description Source wallet (must belong to the caller).
             * @example GAP24RSA…
             */
            fromPublicKey: string;
            /**
             * @description Recipient Stellar address.
             * @example GByEXCHANGE…
             */
            destination: string;
            /**
             * @description Amount of USDC (max 7 decimal places).
             * @example 25.5
             */
            amount: string;
            /**
             * @description Optional memo. Many exchanges require one to credit the deposit.
             * @example 1234567
             */
            memo?: string;
            /**
             * @description Memo type. Exchanges usually specify MEMO_ID (numeric) or MEMO_TEXT.
             * @default text
             * @enum {string}
             */
            memoType: "text" | "id";
        };
        PayContractorDto: {
            /**
             * @description The contractor (payee) to pay.
             * @example a1b2c3d4-…
             */
            contractorId: string;
            /**
             * @description USDC amount (max 7 decimal places).
             * @example 250.5
             */
            amount: string;
            /** @description Which organization treasury pays. Defaults to your org if you own exactly one. */
            organizationId?: string;
            /** @description Optional memo (e.g. for an exchange payee). */
            memo?: string;
            /**
             * @default text
             * @enum {string}
             */
            memoType: "text" | "id";
            /** @description Idempotency key — a retry with the same key never double-pays. */
            idempotencyKey?: string;
        };
        SignUploadDto: {
            /**
             * @description What the image is for; picks the folder + transformation.
             * @enum {string}
             */
            kind: "org-logo" | "avatar";
        };
        CreateDefinitionDto: {
            /** @example Engineering payroll */
            name: string;
            /**
             * @default MONTHLY
             * @enum {string}
             */
            cadence: "MONTHLY" | "BIWEEKLY" | "WEEKLY" | "MANUAL";
            /** @description Default transaction memo for runs. */
            memo?: string;
        };
        UpdateDefinitionDto: {
            name?: string;
            /** @enum {string} */
            cadence?: "MONTHLY" | "BIWEEKLY" | "WEEKLY" | "MANUAL";
            memo?: string;
        };
        UpsertItemDto: {
            /** @description Contractor id (or give `email`). */
            contractorId?: string;
            /** @example kwabena@example.com */
            email?: string;
            /**
             * @description USDC per run (max 7 dp).
             * @example 1200.00
             */
            amount: string;
            note?: string;
            /** @default true */
            active: boolean;
        };
        AdHocLineDto: {
            contractorId: string;
            /** @example 250.00 */
            amount: string;
        };
        CreateRunDto: {
            /** @description Draft from this definition (active items). */
            definitionId?: string;
            /** @description Or explicit lines (max 500). */
            lines?: components["schemas"]["AdHocLineDto"][];
            /** @example March 2026 */
            label: string;
            /** @description Transaction memo (one per batch). */
            memo?: string;
        };
        CreateCashoutDto: {
            /**
             * @description USDC amount, up to your available balance.
             * @example 250
             */
            amount: string;
            /**
             * @description Where to pay it: bank or mobile-money details, as you would give them to an employer.
             * @example GTBank 0123456789 · Ama Serwaa
             */
            destination: string;
            note?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_authProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        magicLink?: boolean;
                        social?: "google"[];
                    };
                };
            };
        };
    };
    WaitlistController_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinWaitlistDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OnboardingController_onboardClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardClientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OnboardingController_onboardContractor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardContractorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_fund: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FundDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_pay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayContractorDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContractorsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContractorsController_lookup: {
        parameters: {
            query: {
                /** @description The contractor’s sign-in email. */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    UploadsController_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    UploadsController_sign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUploadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    PayrollController_listDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_createDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDefinitionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_deleteDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_updateDefinition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDefinitionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_upsertItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_listRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_createRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_discard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PayrollController_execute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReconciliationController_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReconciliationController_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReconciliationController_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CashoutsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CashoutsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCashoutDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CashoutsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
